### ISSUE TITLE
Crashes when trying to comment

### ISSUE THREAD

**Issue by Krusty27** [sk22/megalodon#176]
**Describe the bug**
The app crashes when I click on the comment button.

**To Reproduce**
1. Go to a post in timeline 
2. Click on the comment button
3. Crash

**Version**
Megalodon version: v1.1.5+fork.61

**Additional context**
- Does this issue also occur with the respective upstream release? No

**Comment by sk22** [comment]
well, this doesn't happen to me. this description alone doesn't help me much.

* did this happen on fork version 59?
* does this happen on every post?
* does this happen only on the timeline or everywhere where there's a reply button?
* do the boost, fav and bookmark buttons work?
* can you share a screen recording of the crash?
* you don't happen to have any kind of crash log, do you?

**Comment by sk22** [comment]
oh hang on, i think i just got your error too:

```
Process: org.joinmastodon.android.sk.debug, PID: 11132
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View$OnTouchListener android.widget.PopupMenu.getDragToOpenListener()' on a null object reference
	at me.grishka.appkit.Nav.go(Nav.java:25)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder.onReplyClick(FooterStatusDisplayItem.java:158)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder.$r8$lambda$_Ega7oI5GmQ2kS_Td16Uib8gWC0(Unknown Source:0)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7534)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder.onButtonTouch(FooterStatusDisplayItem.java:140)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder.$r8$lambda$uyZb-Op3WYa-HYYrNk7bjs1blhc(Unknown Source:0)
	at org.joinmastodon.android.ui.displayitems.FooterStatusDisplayItem$Holder$$ExternalSyntheticLambda5.onTouch(Unknown Source:2)
	at android.view.View.dispatchTouchEvent(View.java:15041)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3154)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2813)
```

**Comment by Krusty27** [comment]
Sorry I didn't answer, looks like the last update solved it. Thanks 👍
