### ISSUE TITLE
Switching theme twice crashes the app

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#280]
```
java.lang.IllegalStateException: Fragment HomeTabFragment{7b0a6bf} is not currently in the FragmentManager
	at android.app.FragmentManagerImpl.putFragment(Unknown Source:31)
	at org.joinmastodon.android.fragments.HomeFragment.onSaveInstanceState(HomeFragment.java:260)
	at android.app.Fragment.performSaveInstanceState(Unknown Source:0)
	at android.app.FragmentManagerImpl.saveFragmentBasicState(Unknown Source:14)
	at android.app.FragmentManagerImpl.saveAllState(Unknown Source:112)
	at android.app.FragmentController.saveAllState(Unknown Source:4)
	at android.app.Activity.onSaveInstanceState(Unknown Source:13)
	at me.grishka.appkit.FragmentStackActivity.onSaveInstanceState(FragmentStackActivity.java:341)
	at android.app.Activity.performSaveInstanceState(Unknown Source:3)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Unknown Source:0)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(Unknown Source:44)
	at android.app.ActivityThread.callActivityOnStop(Unknown Source:59)
	at android.app.ActivityThread.handleRelaunchActivityInner(Unknown Source:26)
	at android.app.ActivityThread.handleRelaunchActivity(Unknown Source:343)
	at android.app.servertransaction.ActivityRelaunchItem.execute(Unknown Source:25)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ClientTransactionHandler.executeTransaction(Unknown Source:7)
	at android.app.ActivityThread.handleRelaunchActivityLocally(Unknown Source:85)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:157)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
```

**Comment by sk22** [comment]
in https://github.com/sk22/megalodon/commit/58fd0c444f30aa5352486b97cab34b2aca6ce8ab, i worked around it by forcing an app-restart when exiting the settings, but apparently the same thing (?) happens at random, or when the activity is recreated, i assume.
switching the theme twice crashes the app with the above stack trace, but switching it just once seems to make the fragment load in a corrupted way so that the window insets don't get applied (and the "see new posts" padding in "onViewCreated" (i think?) gets set when the measurement yields 0)
