### ISSUE TITLE
crashes when I open the app

### ISSUE THREAD

**Issue by deanveloper** [sk22/megalodon#430]
**Describe the bug**

When I open the app, it crashes

**To reproduce**

1. open the app
2. it crashes 😱

**Does this happen in the official app?**

No

Does this issue also occur with the respective upstream release?

No

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Megalodon version:

version 1.1.5+fork.76-play

I run a Pixel 7 Pro on Android 13 (Dec 5th security update)

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

I'd love to provide one, but unfortunately don't know how.

**Comment by TheEssem** [comment]
I'm having this same issue, here's a crash log I got through Scoop:
```
FATAL EXCEPTION: main
Process: org.joinmastodon.android.sk, PID: 23970
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at android.graphics.Color.parseColor(Color.java:1383)
	at org.joinmastodon.android.fragments.c6.p1(SourceFile:212)
	at org.joinmastodon.android.fragments.c6.Y(SourceFile:64)
	at u.d.onCreateView(SourceFile:24)
	at android.app.Fragment.performCreateView(Fragment.java:2505)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.Fragment.performActivityCreated(Fragment.java:2520)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
	at android.app.Activity.performCreate(Activity.java:8319)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1421)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
```

**Comment by deanveloper** [comment]
@TheEssem Given that it looks like it's trying to parse a color on launch, what color theme are you using? I use system theme, which might make sense as to why this is occurring?

**Comment by cybersulu** [comment]
I'm experiencing a crash upon opening the app also. I noticed that it only happens when I'm signed in with an owner/admin account. When I change to a regular user role on the same account/server, it no longer crashes.

**Comment by TheEssem** [comment]
> @TheEssem Given that it looks like it's trying to parse a color on launch, what color theme are you using? I use system theme, which might make sense as to why this is occurring?

I have the color set to blue inside the app.

**Comment by deanveloper** [comment]
> I'm experiencing a crash upon opening the app also. I noticed that it only happens when I'm signed in with an owner/admin account. When I change to a regular user role on the same account/server, it no longer crashes.

Yup, I'm an admin as well. I assume that's where the issue stems from then

**Comment by MagicGoddess** [comment]
I'm facing this issue as well, and I'm an admin as well.

**Comment by 0ddfactory** [comment]
Another admin account, same issue it's definitely related

**Comment by TheEssem** [comment]
Yeah, I'm also an admin.

**Comment by hazycora** [comment]
Hi, same, and on another admin account! if the color theme thing is relevant as someone else guessed, I'm pretty sure mine was set to purple.

**Comment by rmford91** [comment]
Having the same issue here. I'm also an admin and my instance is running 4.1.0. Using a Pixel 5a, Android 13. I also noticed if I uninstall the app and then re-install it, the app will work the first time I launch it and keep working until I close the app by swiping it away.

**Comment by parkrocker** [comment]
The problem does not occur in version v1.1.5+fork.74, but it does in all newer versions.
