### ISSUE TITLE
Crash after adding Friendica account

### ISSUE THREAD

**Issue by eengnr** [sk22/megalodon#460]
**Describe the bug**

After updating to Version 1.2.0+fork.79, the app crashes if a Friendica account was added. I know that Friendica most likely is not "officially" supported, but until fork.77, it was at least possible to add an account without any issues.

**To reproduce**

- Reset app data
- Add Friendica account
- App crashes

**Does this happen in the official app?**

No, does not happen in the "upstream" version of Version 1.2.0+fork.79

**Version**

Megalodon version: Version 1.2.0+fork.79

**Comment by sk22** [comment]
huh, i didn't even know it used to be possible to add a friendica account! that implies that it's probably a feature introduced since then. if you're able to provide a crash log, it would greatly help me find the problem as i don't currently have any friendica account to test with

**Comment by eengnr** [comment]
I got this crash log from Scoop:

```
FATAL EXCEPTION: main
Process: org.joinmastodon.android.sk, PID: 31160
java.lang.NullPointerException: Attempt to read from field 'org.joinmastodon.android.model.StatusPrivacy org.joinmastodon.android.model.Source.privacy' on a null object reference in method 'void org.joinmastodon.android.api.session.AccountSessionManager$2.onSuccess(org.joinmastodon.android.model.Account)'
	at org.joinmastodon.android.api.session.AccountSessionManager$2.onSuccess(AccountSessionManager.java:282)
	at org.joinmastodon.android.api.session.AccountSessionManager$2.onSuccess(AccountSessionManager.java:276)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I hope this helps and thanks for looking into it!!
