### ISSUE TITLE
crash when accepting follow request

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#692]

**Comment by sudo42** [comment]
Sadly, still crashed when/directly after[^0] accepting a follow request this week, with version `2.1.6+fork.110`.
(Accepting was successful and the UI displayed the new follow correctly after restarting Megalodon.)

[^0]: nothings happens for about a second or a half after pressing the accept button, then crashes

------

Crash log from adb/logcat:

```
--------- beginning of crash
11-16 09:49:41.822 28267 28296 E AndroidRuntime: FATAL EXCEPTION: MastodonAPIController
11-16 09:49:41.822 28267 28296 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 28267
11-16 09:49:41.822 28267 28296 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'org.joinmastodon.android.model.Account org.joinmastodon.android.model.Status.account' on a null object reference
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at org.joinmastodon.android.model.PushNotification.fromNotification(SourceFile:55)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at org.joinmastodon.android.PushNotificationReceiver.notifyUnifiedPush(SourceFile:153)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1.lambda$onSuccess$0(SourceFile:75)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1.$r8$lambda$4J7AuBytjmt8335OwYDlx1gnhvU(SourceFile:0)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1$$ExternalSyntheticLambda0.run(SourceFile:0)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-16 09:49:41.822 28267 28296 E AndroidRuntime: 	at me.grishka.appkit.utils.WorkerThread.run(SourceFile:54)
```
