### ISSUE TITLE
NPE in HtmlParser.applyFilterHighlights

### ISSUE THREAD

**Issue by brawaru** [sk22/megalodon#774]
**Describe the bug**

So I decided to update Megalodon after a long time thinking redesign update somewhat stabilised (rookie mistake). Now upon launch it just crashes with an NPE.

**To reproduce**

1. Start the app.

**Does this happen in the official app?**

Nope, official app works just fine.

**Screenshots and screen recordings**

N/A.

**Version**

Megalodon version: 2.0.3+fork.98

**Crash log**

```
08-25 18:06:37.412 11504 11504 D AndroidRuntime: Shutting down VM
08-25 18:06:37.413 11504 11504 E AndroidRuntime: FATAL EXCEPTION: main
08-25 18:06:37.413 11504 11504 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 11504
08-25 18:06:37.413 11504 11504 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.ui.text.HtmlParser.applyFilterHighlights(SourceFile:286)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(SourceFile:252)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(SourceFile:43)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(SourceFile:33)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(SourceFile:128)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at me.grishka.appkit.utils.Preloader.onDataLoaded(SourceFile:86)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(SourceFile:327)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.BaseStatusListFragment.onDataLoaded(SourceFile:788)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.HomeTimelineFragment$1.onSuccess(SourceFile:73)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.fragments.HomeTimelineFragment$1.onSuccess(SourceFile:67)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.api.CacheController.lambda$getHomeTimeline$0(SourceFile:78)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.api.CacheController.$r8$lambda$JXT-Ck0tBMUUohbeGHH3DpCpqg0(SourceFile:0)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at org.joinmastodon.android.api.CacheController$$ExternalSyntheticLambda2.run(SourceFile:0)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-25 18:06:37.413 11504 11504 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-25 18:06:37.415  2088  7019 W ActivityManager:   Force finishing activity org.joinmastodon.android.sk/org.joinmastodon.android.MainActivity
```

**Comment by sk22** [comment]
> So I decided to update Megalodon after a long time thinking redesign update somewhat stabilised

well, i haven't had that bug at all. but also, making sure the filtering works as expected (because there were quite some changes to filtering from upstream) is something i'll have to do before releasing a new proper version anyway - and this issue seems to have something to do with filtering.

nevertheless, i see where the null-pointer exception occurs and i think this one-line change should fix the issue
