### ISSUE TITLE
Crash when emojis loaded on emoji bar

### ISSUE THREAD

**Issue by McKristoffer** [sk22/megalodon#920]
**Describe the bug**

Seemingly randomly, megalodon crashes once the emojis on the emoji bar get loaded (the one which is opened by typing ":" and then the emoji tag)

**To reproduce**

Try adding enough emojis, and eventually the app will crash once the emoji images on the emoji picker bar will load

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

No as far as I know

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

![Screenshot_20231103-145240_Megalodon](https://github.com/sk22/megalodon/assets/12572834/c34c3f13-9ba8-450f-98bf-51ad06da1dc1)

**Version**

Megalodon version: the 108 fork, it happened before in the previous pre releases too but didnt have the chance to report this 

**Crash log**

N/A, to be frank i dunno how to obtain this from the app

**Comment by JEKMiles** [comment]
Also getting crashes here, doesn't require typing emojis just changing the text that follows : causea it.
This is the crash log I get
```
2.1.6+fork.110 (110)
2023-11-16T14:15:22.910Z

java.lang.IllegalStateException: Can only create one instance of the view holder. parent=me.grishka.appkit.views.UsableRecyclerView{dd499b8 VFED..... ......I. 0,0-1080,139}, viewType=79
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:24)
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:9)
	at me.grishka.appkit.utils.MergeRecyclerAdapter.onCreateViewHolder(SourceFile:118)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(SourceFile:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:2328)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1629)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:666)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4003)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:2021)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(SourceFile:2060)
	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:1873)
	at org.joinmastodon.android.ui.utils.UiUtils.updateList(SourceFile:896)
	at org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController.setText(SourceFile:214)
	at org.joinmastodon.android.fragments.ComposeFragment.onSelectionChanged(SourceFile:1651)
	at org.joinmastodon.android.ui.views.ComposeEditText.onSelectionChanged(SourceFile:46)
	at android.widget.TextView.spanChange(TextView.java:11239)
	at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:14192)
	at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1308)
	at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:652)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:581)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:941)
	at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:712)
	at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:154)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$setComposingText$25$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:724)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda19.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by McKristoffer** [comment]
Yup, can confirm it still happens on the newest version for me as well, saw that the crashlog can now be grabbed from the About section, here it is:
2.1.6+fork.110 (110)
2023-11-16T21:13:56.906Z

java.lang.IllegalStateException: Can only create one instance of the view holder. parent=me.grishka.appkit.views.UsableRecyclerView{451ca25 VFED..... ......ID 0,0-1080,147}, viewType=37
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:24)
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:9)
	at me.grishka.appkit.utils.MergeRecyclerAdapter.onCreateViewHolder(SourceFile:118)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(SourceFile:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:2328)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1629)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:666)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4003)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:2021)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(SourceFile:2060)
	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:1873)
	at org.joinmastodon.android.ui.utils.UiUtils.updateList(SourceFile:896)
	at org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController.setText(SourceFile:214)
	at org.joinmastodon.android.fragments.ComposeFragment.onSelectionChanged(SourceFile:1651)
	at org.joinmastodon.android.ui.views.ComposeEditText.onSelectionChanged(SourceFile:46)
	at android.widget.TextView.spanChange(TextView.java:11996)
	at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:15278)
	at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1317)
	at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:661)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:590)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:517)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:867)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:177)
	at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:169)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by McKristoffer** [comment]
Adding another crash log in case if needed
```
2.1.6+fork.110 (110)
2023-11-20T08:35:49.572Z

java.lang.IllegalStateException: Can only create one instance of the view holder. parent=me.grishka.appkit.views.UsableRecyclerView{f8b1f57 VFED..... ......I. 0,0-1080,147}, viewType=22
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:24)
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:9)
	at me.grishka.appkit.utils.MergeRecyclerAdapter.onCreateViewHolder(SourceFile:118)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(SourceFile:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:2328)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1629)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:666)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4003)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:2021)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(SourceFile:2060)
	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:1873)
	at org.joinmastodon.android.ui.utils.UiUtils.updateList(SourceFile:896)
	at org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController.setText(SourceFile:214)
	at org.joinmastodon.android.fragments.ComposeFragment.onSelectionChanged(SourceFile:1651)
	at org.joinmastodon.android.ui.views.ComposeEditText.onSelectionChanged(SourceFile:46)
	at android.widget.TextView.spanChange(TextView.java:11996)
	at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:15278)
	at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1317)
	at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:661)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:590)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:517)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:867)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:177)
	at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:169)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by SteffoSpieler** [comment]
Just got it reliably while trying to input `:camera:` (we don't have this emoji on the instance, it crashes every time after the "m")

Crash log:
```
2.1.6+fork.110 (110)
2023-12-03T09:58:10.857Z

java.lang.IllegalStateException: Can only create one instance of the view holder. parent=me.grishka.appkit.views.UsableRecyclerView{8180874 VFED..... ......ID 0,0-1080,147}, viewType=13
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:24)
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:9)
	at me.grishka.appkit.utils.MergeRecyclerAdapter.onCreateViewHolder(SourceFile:118)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(SourceFile:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:2328)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1629)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:666)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4003)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:1991)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(SourceFile:2060)
	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:1873)
	at org.joinmastodon.android.ui.utils.UiUtils.updateList(SourceFile:896)
	at org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController.setText(SourceFile:214)
	at org.joinmastodon.android.fragments.ComposeFragment.startAutocomplete(SourceFile:1677)
	at org.joinmastodon.android.fragments.ComposeFragment.onSelectionChanged(SourceFile:1647)
	at org.joinmastodon.android.ui.views.ComposeEditText.onSelectionChanged(SourceFile:46)
	at android.widget.TextView.spanChange(TextView.java:12527)
	at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:15863)
	at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1308)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:753)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
	at android.text.Selection.setSelection(Selection.java:97)
	at android.text.Selection.setSelection(Selection.java:79)
	at android.view.inputmethod.BaseInputConnection.setSelection(BaseInputConnection.java:810)
	at android.view.inputmethod.InputConnectionWrapper.setSelection(InputConnectionWrapper.java:244)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$setSelection$20(RemoteInputConnectionImpl.java:699)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$4aHOQk1z1BDDOlkyyuEbbUUtjoE(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda9.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by EngineerDali** [comment]
Update: this happened to me just now when trying to tag somebody as well, while the picker bar at the bottom was loading. Heres the crash log: 

```
2.1.6+fork.110 (110)
2023-12-17T14:35:18.110Z

java.lang.IllegalStateException: Can only create one instance of the view holder. parent=me.grishka.appkit.views.UsableRecyclerView{84c89e4 VFED..... ......ID 0,0-1080,147}, viewType=24
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:24)
	at me.grishka.appkit.utils.SingleViewRecyclerAdapter.onCreateViewHolder(SourceFile:9)
	at me.grishka.appkit.utils.MergeRecyclerAdapter.onCreateViewHolder(SourceFile:118)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(SourceFile:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:2328)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1629)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:666)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:4003)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:4569)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
	at android.view.View.layout(View.java:24475)
	at android.view.ViewGroup.layout(ViewGroup.java:7383)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
